# docker-compose-hserverless.yml

version: '3.7'

services:
  h-serverless-running:
    image: airbornarsh/h-serverless-running-service:latest
    env_file:
      - .env
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    expose:
      - 4005
  nginx:
    image: nginx:latest
    ports:
      - '4005:4005'
    depends_on:
      - h-serverless-running
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
